# builder
FROM rust:1.96-slim-bookworm AS builder

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY billing/ ./billing/
COPY mock-psp/ ./mock-psp/
COPY migrations/ ./migrations/
COPY .sqlx/ ./.sqlx/

ENV SQLX_OFFLINE=true

RUN cargo build --release --bin billing

# runtime
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    ca-certificates \
    libssl3 \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/release/billing /app/billing
COPY --from=builder /app/migrations /app/migrations

EXPOSE 8080

CMD ["/app/billing"]